In [1]:
import pandas as pd
import scipy.stats as stats
# https://raw.githubusercontent.com/dataprofessor/
# data/refs/heads/master/penguins_cleaned.csv
url = "https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/penguins_cleaned.csv"
df = pd.read_csv(url)
df.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181,3750,male
1,Adelie,Torgersen,39.5,17.4,186,3800,female

In [2]:
df.corr(numeric_only=True)

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.228626,0.653096,0.589451
bill_depth_mm,-0.228626,1.000000,-0.577792,-0.472016
flipper_length_mm,0.653096,-0.577792,1.000000,0.872979
body_mass_g,0.589451,-0.472016,0.872979,1.000000

In [4]:
r, p = stats.pearsonr(df["body_mass_g"], df["flipper_length_mm"])
r2 = r**2
print(f"r={r:.4f}, p={p:.4f}, r2={r2:.4f}")

r=0.8730, p=0.0000, r2=0.7621

In [9]:
r, p = stats.pearsonr(df["flipper_length_mm"], df["bill_length_mm"])
r2 = r**2
print(r,p,r2)

0.6530956386670859 7.211340708097371e-42 0.4265339132459688